### ISSUE TITLE
cant install plugin

### ISSUE THREAD

**Issue by pavolNovak** [OctoPrint/OctoPrint-Pushbullet#10]
Hi, I wanted to install plugin pushbullet from manager but cant do it. this is what I get. 

```
Installing plugin from https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip...
/home/pi/oprint/bin/python -m pip install https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Collecting https://github.com/OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ea1390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ea1fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ea1ff0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ea1530>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5e80d10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /OctoPrint/OctoPrint-Pushbullet/archive/master.zip
Exception:
Traceback (most recent call last):
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
status = self.run(options, args)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
requirement_set.prepare_files(finder)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 577, in _prepare_file
session=self.session, hashes=hashes)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
hashes=hashes
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
hashes)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 842, in _download_http_url
stream=True,
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 480, in get
return self.request('GET', url, **kwargs)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 378, in request
return super(PipSession, self).request(method, url, *args, **kwargs)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 468, in request
resp = self.send(prep, **send_kwargs)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
resp = super(CacheControlAdapter, self).send(request, **kw)
File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 437, in send
raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /OctoPrint/OctoPrint-Pushbullet/archive/master.zip (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5e380f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Done!
```

**Comment by foosel** [comment]
Your OctoPrint instance doesn't have a connection to the internet, or at the very least cannot resolve github.com:

    [Errno -2] Name or service not known

Nothing the plugin or OctoPrint can solve. Please check your network connection, chances are high updates and similar also don't work for the same reason.
