### ISSUE TITLE
Can't connect to pushbullet , access_token variable is filled in config.yaml and octoprint service has been restarted

### ISSUE THREAD

**Issue by flow23** [OctoPrint/OctoPrint-Pushbullet#2]
2015-08-13 17:35:30,858 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2015-08-13 17:35:31,167 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2015-08-13 17:35:31,484 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): api.pushbullet.com
2015-08-13 17:35:31,859 - octoprint.server.util.sockjs - INFO - New connection from client: 10.0.1.133
2015-08-13 17:35:34,523 - octoprint.plugins.octobullet - ERROR - Error while instantiating PushBullet
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 26, in _connect_bullet
    self._bullet = pushbullet.PushBullet(apikey)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 29, in __init__
    self.refresh()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 267, in refresh
    self._load_devices()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 42, in _load_devices
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 35, in _get_data
    raise InvalidKeyError()
InvalidKeyError

**Comment by foosel** [comment]
Please double check your access token. That error is thrown if pushbullet doesn't accept your token.

**Comment by flow23** [comment]
I repasted the Access Token and clicked "Save". Now it works. Thank you.
