### ISSUE TITLE
Webcam rotate/flip issue - TypeError: sequence item 3: expected string, instance found

### ISSUE THREAD

**Issue by denix0** [OctoPrint/OctoPrint-Pushbullet#34]
Latest install of Raspbian - apt update, apt upgrade.
Latest version of OctoPrint 1.5.1
Python 2.7.16

Error sending Pushbullet messages:

2020-12-07 19:48:35,690 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin octobullet
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 146, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 234, in on_api_command
    result = self._send_message_with_webcam_image("Test from the OctoPrint PushBullet Plugin", message, sender=sender)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 365, in _send_message_with_webcam_image
    self._process_snapshot(tempFile)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 447, in _process_snapshot
    self._logger.info("Running: {}".format(" ".join(ffmpeg_command)))
TypeError: sequence item 3: expected string, instance found

**Comment by denix0** [comment]
Checking the code in __init__.py around line 447, it tries to call ffmpeg to rotate/flip the image, which my webcam requires. After disabling rotate/flip settings, Pushbullet works as expected.
